### ISSUE TITLE
Open settings on left side

### ISSUE THREAD

**Issue by MoonPadUSer** [instantOS/instantSETTINGS#12]
In my opinion it's not very nice that when you open instantsettings via the toggle in the top left corner, it opens on the right side, so you have to move your mouse all the way to the other side of your screen, that's why I'd recommend opening instantSettings on the left side of the screen by default

**Comment by uvera** [comment]
Can be closed since https://github.com/instantOS/instantSETTINGS/commit/aba94161033f6fdf673fbfdadf9133414df6e810
